version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 5

  crm_adapter:
    build:
      context: .
      dockerfile: Dockerfile_CRM
    container_name: crm_adapter_service
    environment:
      # Настройки для реальной CRM
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      CREATIO_URL: https://your.real-creatio.com # <-- ОБНОВИ ЭТОТ URL
      CREATIO_AUTH_URL: /AuthService.svc/Login
      CREATIO_UPDATE_ORDER_URL: /odata/Order(guid'{order_id}')
      CREATIO_USERNAME: your_real_username # <-- ОБНОВИ ЭТО ИМЯ ПОЛЬЗОВАТЕЛЯ
      CREATIO_PASSWORD: your_real_password # <-- ОБНОВИ ЭТОТ ПАРОЛЬ
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python CRMAdapter.py

  dms_adapter:
    build:
      context: .
      dockerfile: Dockerfile_DMS
    container_name: dms_adapter_service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python DMSAdapter.py

  onec_adapter:
    build:
      context: .
      dockerfile: Dockerfile_OneC
    container_name: onec_adapter_service
    ports:
      - "5000:5000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      FLASK_PORT: 5000
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: python OneCAdapter.py
