FROM python:3.9-slim-buster

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all necessary application files
COPY rabbitmq.py .
COPY OneCAdapter.py .
COPY .env .

# Expose the port for the Flask server
EXPOSE 5000

# Command to run the OneCAdapter.py script when the container starts
CMD ["python", "OneCAdapter.py"]
