FROM python:3.9-slim-buster

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY rabbitmq.py .
COPY CRMAdapter.py .
COPY .env .

# Command to run the CRMAdapter.py script when the container starts
CMD ["python", "CRMAdapter.py"]